#!/bin/bash
# install-node-tool-shims.sh — install PATH shims for the Node tools a project's
# verification steps invoke (eslint, prettier, tsc, ava, ...), resolving each one
# from the CALLER'S tree at run time.
#
# Usage: install-node-tool-shims.sh [<bin-dir>]
#   <bin-dir>  where to write the shims (default "$HOME/.local/bin")
#
# Why these shims exist at all: the container mounts the tree in a way that
# blocks exec straight out of `node_modules/.bin`, so a verification step that
# dispatches through a package bin dies locally while the identical script is
# green on CI. `skills/local-verify/SKILL.md` § Parity is the contract names that
# class of divergence and requires closing it by PROVIDING the shims, never by
# accepting the skipped step.
#
# Why this script exists: the shims used to be hand-written by whichever job first
# needed one, each `exec node <that job's worktree>/node_modules/<tool>/...`. A
# per-job worktree is torn down when its job ends, so every such shim became a
# dangling absolute path pointing into a deleted directory. It then fails one of
# two ways, and the second is worse than the first:
#
#   1. Loudly, with MODULE_NOT_FOUND, once the pinned worktree is gone.
#   2. QUIETLY LINTING THE WRONG TREE, while the pinned worktree still exists.
#      A gardener runs `eslint` in its own checkout, the shim resolves a peer's
#      checkout instead, and a green result says nothing about the code about to
#      be pushed.
#
# Observed 2026-07-29: all four of this host's shims (eslint, prettier, tsc, ava)
# pointed into `project-wt-...-pr761-shepherd-...`, a worktree deleted days
# earlier, so every lint/type/test step dispatching through them was broken
# host-wide.
#
# The fix is that a shim must not name a tree at all. Each one written here walks
# UP from `$PWD` at invocation time to the nearest enclosing `node_modules`
# holding that tool, which is exactly the resolution the caller wants and is
# correct for every worktree, concurrently, with no reinstall between jobs.

set -euo pipefail
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=../common.sh
source "$HERE/../common.sh"
# shellcheck disable=SC2034  # read by common.sh's log()
GARDEN_TAG="install-node-tool-shims"

BIN_DIR="${1:-$HOME/.local/bin}"
mkdir -p "$BIN_DIR"

# tool -> candidate entrypoints relative to a node_modules directory, in
# preference order. Several tools moved their entrypoint between major versions
# (ava's `cli.js` became `cli.mjs`), so each tool carries every spelling we have
# seen rather than pinning one and breaking on upgrade.
emit_shim() {  # emit_shim <tool> <candidate>...
  local tool="$1"; shift
  local dest="$BIN_DIR/$tool"
  {
    printf '#!/usr/bin/env bash\n'
    printf '# Generated by scripts/jobs/gardening/install-node-tool-shims.sh.\n'
    printf '# Resolves %s from the nearest enclosing node_modules, walking up\n' "$tool"
    printf '# from $PWD. Deliberately names no worktree: a per-job worktree is\n'
    printf '# torn down when its job ends, and a shim pinned to one either dies\n'
    printf '# with MODULE_NOT_FOUND or, worse, silently runs against a peer.\n'
    printf 'set -euo pipefail\n'
    printf 'candidates=(%s)\n' "$(printf '%q ' "$@")"
    cat <<'BODY'
dir="$PWD"
while :; do
  for rel in "${candidates[@]}"; do
    if [ -f "$dir/node_modules/$rel" ]; then
      exec node "$dir/node_modules/$rel" "$@"
    fi
  done
  [ "$dir" = / ] && break
  dir="$(dirname "$dir")"
done
BODY
    printf 'printf "%%s\\n" "%s: no node_modules/{%s} above $PWD" >&2\n' \
      "$tool" "$(printf '%s,' "$@" | sed 's/,$//')"
    printf 'exit 127\n'
  } > "$dest"
  chmod +x "$dest"
  log "installed $dest"
}

emit_shim eslint   eslint/bin/eslint.js
emit_shim prettier prettier/bin/prettier.cjs prettier/bin-prettier.js
emit_shim tsc      typescript/bin/tsc
emit_shim ava      ava/entrypoints/cli.mjs ava/entrypoints/cli.js
emit_shim tsd      tsd/dist/cli.js

log "node tool shims installed into $BIN_DIR (resolve relative to \$PWD)"
