#!/usr/bin/env bash
# scrub.sh — runs ON the builder (as root, via SSM) immediately before CreateImage.
# Removes every credential, machine-identity, and history artifact so the AMI is a
# clean, credential-free template. The design is explicit: scrub "package caches,
# machine identity, shell history, Docker credentials, and every home-directory
# credential before CreateImage."
#
# This is defence in depth: the bake never LOGS IN to Claude or GitHub, so there
# should be nothing to find — but we prove it and strip anything that slipped in
# (an operator who re-used the builder, a cached token) rather than trusting the
# happy path.
set -uo pipefail

echo "== scrub: package caches =="
apt-get clean || true
rm -rf /var/lib/apt/lists/* || true

echo "== scrub: machine identity (regenerated on next boot) =="
: > /etc/machine-id || true
rm -f /var/lib/dbus/machine-id || true
# SSH host keys — regenerated by ssh's first-boot unit / cloud-init.
rm -f /etc/ssh/ssh_host_* || true

echo "== scrub: cloud-init state (so the AMI re-inits cleanly per launch) =="
cloud-init clean --logs 2>/dev/null || true

echo "== scrub: shell history, logs, tmp =="
rm -f /root/.bash_history /home/*/.bash_history || true
rm -rf /var/log/*.log /var/log/cloud-init*.log /var/log/journal/* || true
rm -rf /tmp/* /var/tmp/* || true

echo "== scrub: Docker credentials + any home-dir credential material =="
# Docker registry creds (config.json auths), if any tool wrote them.
rm -f /root/.docker/config.json /home/*/.docker/config.json || true
# Claude / GitHub / cloud credentials that must NEVER ship in the AMI.
rm -rf /home/*/.claude/.credentials.json /home/*/.claude/credentials* \
       /home/*/.config/claude* /home/*/.config/gh /home/*/.config/anthropic \
       /home/*/.aws /root/.aws \
       /home/*/.netrc /root/.netrc \
       /home/*/.ssh/authorized_keys 2>/dev/null || true

echo "== scrub: PROVE no residual auth (fail the bake if any is found) =="
found=0
# gh hosts token
if find /home /root -name 'hosts.yml' -path '*gh*' 2>/dev/null | grep -q .; then
  echo "!! gh credential store present after scrub" >&2; found=1
fi
# claude credentials
if find /home /root -path '*claude*' -name '*.credentials.json' 2>/dev/null | grep -q .; then
  echo "!! claude credential present after scrub" >&2; found=1
fi
# aws credentials
if find /home /root -path '*.aws/credentials' 2>/dev/null | grep -q .; then
  echo "!! aws credential present after scrub" >&2; found=1
fi
if [[ "$found" -ne 0 ]]; then
  echo "== scrub: FAILED — residual credential material found; refusing to image ==" >&2
  exit 1
fi
echo "== scrub: clean — no residual credential material =="
sync
echo "== scrub: DONE =="
