// build.mjs — the bulletin's CI renderer. Run by the `bulletin` GitHub Actions
// workflow (Node, no dependencies). It reads the live `journal2` content checked
// out at <content-dir> and assembles a static site at <out-dir> from the app
// source at <app-dir>:
//
//   1. copy the static app source (html/js/css + DESIGN/SETUP) into <out-dir>,
//   2. bake journal2:README.md and the unread maintainer-inbox messages into
//      <out-dir>/data.js as `window.GARDEN_BULLETIN_DATA`,
//   3. emit a `.nojekyll` marker and a root redirect so the site keeps serving
//      at <pages-origin>/garden/bulletin/.
//
// Nothing is committed: the workflow uploads <out-dir> as the Pages artifact and
// deploys it. journal2 is read, never written here. The reply (write) path stays
// pure client-side in github.js, gated on a pasted fine-grained PAT.
//
// Usage: node build.mjs <app-dir> <content-dir> <out-dir>

import { promises as fs } from 'node:fs';
import path from 'node:path';

const [appDir, contentDir, outDir] = process.argv.slice(2);
if (!appDir || !contentDir || !outDir) {
  console.error('usage: node build.mjs <app-dir> <content-dir> <out-dir>');
  process.exit(2);
}

// The static assets copied verbatim into the bulletin/ subdirectory of the site.
const APP_ASSETS = [
  'index.html',
  'app.js',
  'github.js',
  'markdown.js',
  'config.js',
  'style.css',
  'DESIGN.md',
  'SETUP.md',
];

// Parse the bus message format: leading `key: value` lines, a `---` fence, body.
function parseMessage(text) {
  const lines = text.split('\n');
  const fm = {};
  let i = 0;
  for (; i < lines.length; i++) {
    if (lines[i].trim() === '---') {
      i++;
      break;
    }
    const m = lines[i].match(/^([A-Za-z_][\w]*):\s*(.*)$/);
    if (m) fm[m[1]] = m[2].trim();
  }
  return { fm, body: lines.slice(i).join('\n').trim() };
}

async function readOr(file, fallback) {
  try {
    return await fs.readFile(file, 'utf8');
  } catch (e) {
    if (e.code === 'ENOENT') return fallback;
    throw e;
  }
}

async function listUnread(dir) {
  let names;
  try {
    names = await fs.readdir(dir);
  } catch (e) {
    if (e.code === 'ENOENT') return [];
    throw e;
  }
  return names.filter((n) => n.endsWith('.md') && n !== '.gitkeep').sort();
}

async function main() {
  const bulletinOut = path.join(outDir, 'bulletin');
  await fs.mkdir(bulletinOut, { recursive: true });

  // 1. copy static app source.
  for (const name of APP_ASSETS) {
    await fs.copyFile(path.join(appDir, name), path.join(bulletinOut, name));
  }

  // 2. bake journal2 content.
  const readme = await readOr(path.join(contentDir, 'README.md'), '');
  const unreadDir = path.join(contentDir, 'inbox', 'maintainer', 'unread');
  const messages = [];
  for (const name of await listUnread(unreadDir)) {
    const text = await readOr(path.join(unreadDir, name), '');
    const { fm, body } = parseMessage(text);
    messages.push({ name, fm, body });
  }
  const renderedAt = new Date().toISOString().replace(/\.\d+Z$/, 'Z');
  const data = { renderedAt, readme, messages };
  const dataJs =
    '// Generated by bulletin/build.mjs at deploy time — do not edit.\n' +
    `window.GARDEN_BULLETIN_DATA = ${JSON.stringify(data, null, 2)};\n`;
  await fs.writeFile(path.join(bulletinOut, 'data.js'), dataJs);

  // 3. site-level markers and a root redirect to keep the /bulletin/ URL.
  await fs.writeFile(path.join(outDir, '.nojekyll'), '');
  await fs.writeFile(
    path.join(outDir, 'index.html'),
    `<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <title>Garden</title>
    <meta http-equiv="refresh" content="0; url=bulletin/" />
  </head>
  <body>
    <p>Redirecting to the <a href="bulletin/">garden bulletin</a>.</p>
  </body>
</html>
`,
  );

  console.log(
    `bulletin: rendered ${messages.length} maintainer message(s), README ${readme.length} bytes, at ${renderedAt}`,
  );
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
